name: PRAgent
on:
  pull_request:
    branches: ["*"]
  issue_comment:
    types: [opened, reopened, ready_for_review, created]

jobs:
  pr_agent_job:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
      contents: write
    name: Run pr agent on every pull request, respond to user comments
    steps:
      - name: PR Agent action step
        id: pragent
        uses: Codium-ai/pr-agent@main
        env:
          OPENAI_KEY: ${{ secrets.OPENAI }}
          GITHUB_TOKEN: ${{ secrets.CR_GH_TOKEN }}
          PR_DESCRIPTION_USE_DESCRIPTION_MARKERS: "true"
          PR_DESCRIPTION_INCLUDE_GENERATED_BY_HEADER: "true"
          GITHUB_ACTION_AUTO_REVIEW: "true"
          GITHUB_ACTION_AUTO_DESCRIBE: "true"
          GITHUB_ACTION_AUTO_IMPROVE: "true"
          GITHUB_ACTION_AUTO_TEST: "true"
          PR_UPDATE_CHANGELOG_PUSH_CHANGELOG_CHANGES: "true"
          [pr_test] # /test #
          extra_instructions = ""
          testing_framework = "" # specify the testing framework you want to use
          num_tests=3            # number of tests to generate. max 5.
          avoid_mocks=true       # if true, the generated tests will prefer to use real objects instead of mocks
          file = ""              # in case there are several components with the same name, you can specify the relevant file
          class_name = ""        # in case there are several methods with the same name in the same file, you can specify the relevant class name
          enable_help_text=false

      - name: Check action output
        run: echo "${{ steps.pragent.outputs }}"
